### ISSUE TITLE
'multifor' is not a registered tag library.

### ISSUE THREAD

**Issue by justAcoderguy** [gabrielgrant/django-multiforloop#9]
I have tried to configure this library in my project.

However it is not recognizing the tage multifor as a valid one. 

I have followed these steps while configuring :
1. pip install django-multiforloop
2. Include 'multiforloop' in your settings.py's list of installed apps
3. Add `{% load multifor %}` to the top of any templates which use the multiforloop

Could someone please help me out. Thanks!

**Comment by privatealee** [comment]
I am also currently having this issue. Did you ever figure it out?

**Comment by justAcoderguy** [comment]
@privatealee Nope, I didn't. Resorted to using the zip(x,y) function in python. Passing the zipped contents from the backend to the frontend and then using the usual jinja for loop. 
`{% for x,y in zipped %}`
Its a workaround for sure but its our best bet for now..
Hope this helps

**Comment by gabrielgrant** [comment]
Sorry for not getting back to this sooner. This lib was originally written (and afaict is still working) for Django 1.x, but it seems later versions of Django have changed something about how tags are registered. Which version of Django are you using?

**Comment by gabrielgrant** [comment]
Woops, that comment is totally off-base -- it turns out the packaging changes (fixes) that had been made in this repo a while ago had never gotten pushed to PyPI. Just updated all the packaging and published version 0.3.1, which should fix this issue (and several others).

Going to close the issue, but please feel free to reopen if you're still running into issues
